#!/usr/bin/env bash

STOW_DIR=~/.dotfiles # `dirname $0`

pushd $STOW_DIR >/dev/null

case $1 in
linux)
  packages="zsh i3 tmux nvim"
  ;;
mac)
  packages="zsh tmux nvim"
  ;;
*)
  echo "Invalid "
  exit 1
  ;;
esac

for package in $packages; do
  echo -n "Stowing $package...  "
  output=$(stow -R $package 2>&1)
  result=$?
  if [ $result -eq 0 ]; then
    echo "ok"
  else
    echo "ERROR: $output"
  fi
done

popd
